name: u-boot-mt7688-ci

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
      
      - name: Compile u-boot
        env:
          DEBIAN_FRONTEND: noninteractive
        run:  |
          docker rmi `docker images -q`
          tar -jxvf ./buildroot-gcc342.tar.bz2 -C /opt
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential binutils git autoconf automake openjdk-11-jre
          make

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: mt7688 u-boot
          path: uboot.bin
